version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: dev-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
