spring:
  application:
    name: mumuca-diet
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 300
  sql:
    init:
      mode: always

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

bcrypt:
  salt: 13
