spring:
  application:
    name: mumuca-diet
  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    driver-class-name: org.postgresql.Driver
    username: devuser
    password: devpassword
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 30
    open-in-view: false
  h2:
    console:
      enabled: false

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

bcrypt:
  salt: 13