server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json
spring:
  application:
    name: gateway
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - '*'
            allowCredentials: true
            maxAge: 3600
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s
        pool:
          max-connections: 100
          max-idle-time: 10s

apiUrl: http://localhost:8081

rate-limiter:
  public-route:
    replenish-rate: 20
    burst-capacity: 5000
    requested-token: 100
  private-route:
    replenish-rate: 20
    burst-capacity: 20000
    requested-token: 100