server:
  port: ${APP_PORT}
  compression:
    enabled: true
    mime-types: application/json

spring:
  application:
    name: gateway
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - ${DOMAIN_URL}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - '*'
            allowCredentials: true
            maxAge: 3600
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s
        pool:
          max-connections: 100
          max-idle-time: 10s

apiUrl: ${API_URL}

rate-limiter:
  public-route:
    replenish-rate: 20
    burst-capacity: ${PUBLIC_RATE_LIMIT:5000}
    requested-token: 100
  private-route:
    replenish-rate: 20
    burst-capacity: ${PRIVATE_RATE_LIMIT:20000}
    requested-token: 100